import mongoose from "mongoose";
const user = new mongoose.Schema({
    email:{
        type:String,
        required:true,
        unique:true
    },
    username:{
        type:String
    },
    firebaseUid:{
        type:String,
        required:true 
    },
    Name:{
        type:String,
    },
    Profile:{
        type:String,
    },
    Linkedin:{
        type:String,
    },
    twitter:{
        type:String,
    },
    AboutMe:{
        type:[{}]
    },
    workExperience:{
        type:[{}]
    },
    education:{
        type:[{}]
    },
    JobUploaded:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Applicant"
    }],
    Application:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Applicant"
    }],
    },{
    timestamps:true
})
export const User = mongoose.model("User",user)